language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
# command to install dependencies
install:
  - pip install travis-sphinx
  - pip install numpydoc
  - pip install sphinx_rtd_theme
  - pip install .

notifications:
  slack: qtim:jp1UTPVP5wscM2R6eyFHJIb4

script: 
  - "python ./deepneuro/testing/package_test.py"
  - travis-sphinx --nowarn build
    
after_success:
  - travis-sphinx deploy